# Quest -- BONUS: the finished RPG (step 8) re-skinned with REAL CC0 pixel art.
#
# The game logic matches step8_quest.py; the BITMAPS are replaced. The tileset is
# Kenney "Tiny Dungeon" (CC0): our tile values now draw real tiles (floor / floor /
# lava / barrel / brick wall / door / chest), so a "dungeon" falls out of the same
# map. The hero, slime and coins are Tiny Dungeon sprites. Camera, collision, combat,
# dialog, quest and the State object follow step 8.
#
# These sprites are single-frame, so the hero deliberately has no walk/facing animation.
# To keep the walk cycle, provide multiple poses and configure AnimatedSprite as shown in
# step 4. Assets generated by tools/png2picogame from assets/kenney/td/* (CC0, see
# assets/kenney/CREDITS.txt). Use your own art the same way -> tutorials/ASSETS.md.
#
# Run:  python3 sim/run.py tutorials/03-quest/bonus_art.py --shot /tmp/qbonus.png

import terminalio
import picogame as pg
import picogame_game
import picogame_input
import picogame_clock
import picogame_shapes as shp
import picogame_ui as ui
import art_tiles                              # <-- all generated from CC0 PNGs
import art_hero
import art_slime
import art_coin

W, H = 320, 240
TILE = 16
SPEED = 2
MAP = [
    "##############################",
    "#.....:......................#",
    "#.....:........*.............#",
    "#..##.:.............~~~~~~...#",
    "#..##.:.............~~~~~~...#",
    "#.....N.............~~~~~~...#",
    "#.....:.......E.....~~~~~~...#",
    "#.....:......................#",
    "#.....:.....*.........*......#",
    "#.....:......................#",
    "#:::::::P:::::::::*::::::::::#",
    "#.....:...................*..#",
    "#.....:.............E........#",
    "#.....:...WWWWWWW............#",
    "#.....:...W.....W......##....#",
    "#.....:.*.W..G..W......##....#",
    "#.....:...W.....W........E...#",
    "#.....:...WWWDWWW............#",
    "#.....:......................#",
    "##############################",
]
MAPCOLS, MAPROWS = 30, 20
CH2TILE = {".": 1, "P": 1, "N": 1, "*": 1, "E": 1, ":": 2, "~": 3, "#": 4,
           "W": 5, "D": 6, "G": 7}
SOLID = (3, 4, 5, 6)
DOWN, UP, LEFT, RIGHT = 0, 1, 2, 3
DIR = {DOWN: (0, 1), UP: (0, -1), LEFT: (-1, 0), RIGHT: (1, 0)}
EXPLORE, DIALOG, WON = 0, 1, 2                # game modes (int constants, not strings)
BG = pg.rgb565(0, 0, 0)
WHITE = pg.rgb565(255, 255, 255)
NAVY = pg.rgb565(10, 10, 40)

scene, buffer_a, buffer_b = picogame_game.setup(background=BG)
btn = picogame_input.Buttons()
clock = picogame_clock.Clock(30)

tileset = art_tiles.bitmap(pg)                # <-- real tiles; values 1..7 = frames 1..7
world = pg.Tilemap(tileset, MAPCOLS, MAPROWS)
START = (TILE, TILE)
npc_x, npc_y = TILE, TILE
coin_spots, enemy_spots, door_tiles = [], [], []
for tile_y in range(MAPROWS):
    for tile_x in range(MAPCOLS):
        ch = MAP[tile_y][tile_x] if tile_x < len(MAP[tile_y]) else "."
        world.tile(tile_x, tile_y, CH2TILE.get(ch, 1))
        if ch == "P":
            START = (tile_x * TILE, tile_y * TILE)
        elif ch == "N":
            npc_x, npc_y = tile_x * TILE, tile_y * TILE
        elif ch == "*":
            coin_spots.append((tile_x * TILE, tile_y * TILE))
        elif ch == "E":
            enemy_spots.append((tile_x * TILE, tile_y * TILE))
        elif ch == "D":
            door_tiles.append((tile_x, tile_y))
scene.add(world)

coin_bm = art_coin.bitmap(pg)                 # <-- real coin tile (16x16)
coins = [pg.Sprite(coin_bm, x, y) for (x, y) in coin_spots]
for c in coins:
    scene.add(c)
slime_bm = art_slime.bitmap(pg)               # <-- real slime sprite (16x16)
enemies = [pg.Sprite(slime_bm, x, y) for (x, y) in enemy_spots]
for e in enemies:
    scene.add(e)
npc = pg.Sprite(shp.rect(TILE, TILE, pg.rgb565(230, 200, 60)), npc_x, npc_y)
scene.add(npc)

hero = pg.Sprite(art_hero.bitmap(pg), START[0], START[1], frame=0)   # <-- real hero (1 frame)
scene.add(hero)
hud = ui.SceneLabel(scene, pg, terminalio.FONT, 4, 4, WHITE, BG)
dlg = ui.TextBox(pg, terminalio.FONT, 8, H - 64, W - 16, 58, WHITE, NAVY, maxlines=4)
NUMCOINS = len(coins)


class State:
    """The whole game's mutable state -- one object, passed where a function needs it."""
    def __init__(self):
        self.facing = DOWN
        self.got = 0                     # coins collected
        self.hp = 6
        self.hurt_cooldown = 0
        self.stage = 0                   # 0 not started, 1 collecting, 2 door open
        self.mode = EXPLORE             # EXPLORE / DIALOG / WON
        self.frame = 0
        self.overlay_shown = False       # draw dialog/win modal once, not every frame


st = State()


def solid_at(pixel_x, pixel_y):
    tile_x, tile_y = pixel_x // TILE, pixel_y // TILE
    if tile_x < 0 or tile_x >= MAPCOLS or tile_y < 0 or tile_y >= MAPROWS:
        return True
    return world.tile(tile_x, tile_y) in SOLID


def can_walk(pixel_x, pixel_y):
    return not (solid_at(pixel_x + 2, pixel_y + 2) or solid_at(pixel_x + TILE - 3, pixel_y + 2) or
                solid_at(pixel_x + 2, pixel_y + TILE - 3) or solid_at(pixel_x + TILE - 3, pixel_y + TILE - 3))


def near(a, bx, by, d=TILE):
    return abs(a.x - bx) < d and abs(a.y - by) < d


def camera_follow():
    offset_x = max(W - MAPCOLS * TILE, min(0, W // 2 - (hero.x + TILE // 2)))
    offset_y = max(H - MAPROWS * TILE, min(0, H // 2 - (hero.y + TILE // 2)))
    scene.set_view(int(offset_x), int(offset_y))


def dialog_lines(st):
    if st.stage == 0:
        return ["Villager:", "Bring me all %d coins and" % NUMCOINS,
                "I'll open the shrine door.", "(press A)"]
    if st.stage == 1 and st.got < NUMCOINS:
        return ["Villager:", "You have %d of %d coins." % (st.got, NUMCOINS),
                "Keep looking!", "(press A)"]
    return ["Villager:", "The door is open.",
            "Seek the shrine within.", "(press A)"]


def open_door():
    for (tile_x, tile_y) in door_tiles:
        world.tile(tile_x, tile_y, 2)                 # door -> path (no longer SOLID)
    scene.invalidate()


camera_follow()
while True:
    btn.poll()
    st.frame += 1

    if st.mode == WON:
        if not st.overlay_shown:              # draw ONCE -> no per-frame flicker
            scene.refresh()
            dlg.draw(scene.display, buffer_a, ["You reached the shrine!", "", "QUEST COMPLETE", "(press A)"])
            st.overlay_shown = True
        if btn.just_pressed(btn.A):
            st.mode = EXPLORE; scene.invalidate()
        clock.tick()
        continue

    if st.mode == DIALOG:
        if not st.overlay_shown:              # draw ONCE -> no per-frame flicker
            scene.refresh()
            dlg.draw(scene.display, buffer_a, dialog_lines(st))
            st.overlay_shown = True
        if btn.just_pressed(btn.A) or btn.just_pressed(btn.B):
            if st.stage == 0:
                st.stage = 1
            elif st.stage == 1 and st.got >= NUMCOINS:
                st.stage = 2
                open_door()
            st.mode = EXPLORE; scene.invalidate()
        clock.tick()
        continue

    delta_x = btn.is_pressed(btn.RIGHT) - btn.is_pressed(btn.LEFT)
    delta_y = btn.is_pressed(btn.DOWN) - btn.is_pressed(btn.UP)
    if delta_x:
        st.facing = RIGHT if delta_x > 0 else LEFT
    elif delta_y:
        st.facing = DOWN if delta_y > 0 else UP
    moved = False
    if delta_x and can_walk(hero.x + delta_x * SPEED, hero.y):
        hero.move(hero.x + delta_x * SPEED, hero.y); moved = True
    if delta_y and can_walk(hero.x, hero.y + delta_y * SPEED):
        hero.move(hero.x, hero.y + delta_y * SPEED); moved = True
    if moved:
        camera_follow()

    if btn.just_pressed(btn.B):
        ddx, ddy = DIR[st.facing]
        ax, ay = hero.x + ddx * TILE, hero.y + ddy * TILE
        for e in enemies:
            if e.visible and abs(e.x - ax) < TILE and abs(e.y - ay) < TILE:
                e.visible = False

    if st.frame % 2 == 0:
        for e in enemies:
            if not e.visible:
                continue
            sx = (hero.x > e.x) - (hero.x < e.x)
            sy = (hero.y > e.y) - (hero.y < e.y)
            if sx and can_walk(e.x + sx, e.y):
                e.move(e.x + sx, e.y)
            if sy and can_walk(e.x, e.y + sy):
                e.move(e.x, e.y + sy)

    if st.hurt_cooldown > 0:
        st.hurt_cooldown -= 1
    else:
        for e in enemies:
            if e.visible and near(e, hero.x, hero.y, 13):
                st.hp -= 1
                st.hurt_cooldown = 40
                if st.hp <= 0:
                    st.hp = 6
                    hero.move(START[0], START[1]); camera_follow()
                break

    for c in coins:
        if c.visible and abs(hero.x - c.x) < 12 and abs(hero.y - c.y) < 12:
            c.visible = False; st.got += 1

    # reach the shrine (goal tile) once the door is open
    if st.stage >= 2:
        ctx = (hero.x + TILE // 2) // TILE
        cty = (hero.y + TILE // 2) // TILE
        if world.tile(ctx, cty) == 7:
            st.mode = WON; st.overlay_shown = False

    if near(hero, npc.x, npc.y):
        hud.set("HP %d  COINS %d/%d  A:TALK" % (st.hp, st.got, NUMCOINS))
        if btn.just_pressed(btn.A):
            st.mode = DIALOG; st.overlay_shown = False
    else:
        obj = "FIND THE COINS" if st.stage < 1 or st.got < NUMCOINS else ("DOOR OPEN!" if st.stage >= 2 else "RETURN TO NPC")
        hud.set("HP %d  COINS %d/%d  %s" % (st.hp, st.got, NUMCOINS, obj))

    scene.refresh()
    clock.tick()
