# Generated by tools/picolib_img.py from a PicoLibSDK image - do not edit.
# Original art (c) its PicoLibSDK author; converted to picogame PAL8.
# FULL-RES original layer 2 (640x64 @1x, PicoLibSDK 01meadow2) - FAT-XIP makes the 40 KB free.
# SPLIT variant (ROMFS asset pipeline): pixels live in meadow2.bin - pack it into the game's
# assets .romfs (tools/build_romfs.py). Only the palette stays in RAM; on a board with an
# asset region the pixels blit 0-copy from XIP flash, elsewhere data() reads the sibling file.
import array

W = 640      # frame width
H = 64
FRAMES = 1
STRIDE = 640
TRANSP = 1
BIN = 'meadow2f.bin'

PAL = array.array("H", [0, 65535, 8568, 10746, 64510, 58816, 17304, 1777, 17624, 17328, 38901, 56286, 32503, 58400, 49151, 24303, 8448, 49143, 25096, 49944, 1049, 65527, 48879, 41480, 34330, 42538, 18483, 33561, 10044, 50474, 9250, 58929, 24840, 65271, 42810, 17723, 34627, 43876, 17978, 25941, 59466, 25906, 9522, 58188, 42025, 18779, 8218, 2140, 51811, 48367, 43116, 11116, 26451, 8729, 44412, 42059, 18549, 9803, 41002, 51052, 42042, 58690, 25914, 25377, 16724, 9266, 33330, 835, 17500, 9547, 26195, 10067, 42570, 47054, 8507, 57641, 42092, 25939, 42306, 28070, 10604, 50259, 1917, 25658, 59235, 42843, 41769, 60804, 25683, 58979, 43900, 11669, 15335, 33099, 42050, 10092, 26459, 25121, 43132, 58698, 9811, 36509, 19068, 9530, 49688, 17449, 604, 9324, 42876, 42851, 51307, 38086, 22751, 24940, 57972, 50556, 58442, 25947, 9555, 26203, 19349, 52108, 50481, 42595, 59243, 10356, 25922, 4798, 9299, 58987, 9274, 29093, 25435, 10100, 51588, 42314, 16673, 42347, 10389, 25666, 20158, 50225, 17301, 41546, 9596, 57905, 42892, 41232, 1883, 57649, 9563, 49969, 42859, 9819, 61654, 11107, 41835, 42058, 42603, 50514, 50770, 42380, 1115, 26211, 51315, 18531, 50547, 18052, 17763, 50803, 51059, 17994, 10372, 44725, 9604, 51100, 25129, 35765, 2981, 8737, 25385, 8993, 8192, 64222, 65279, 23791, 42396, 10413, 1090, 25930, 17300, 58210, 25674, 54717, 19084, 11949, 22478, 58540, 59341, 26301, 24584, 26598, 1346, 47070, 33989, 47574, 48631, 17564, 17523, 4343, 61645, 37565, 11916, 52091, 39423, 23535, 10140, 19686, 18291, 13815, 28052, 46310, 13774, 43989, 44956, 20966, 21718, 54213, 6383, 850, 18002, 2253, 55270, 18108, 42850, 25954, 1354, 4525, 22238, 9001, 8867, 10875, 25649, 8521, 44435, 32247, 19139, 26578, 49768, 1698, 25737, 61427, 8264, 48895, 65535, 48887])


def data(root=""):
    """The raw PAL8 pixels: a memoryview into XIP flash when the ROMFS asset region is
    mounted (0-copy; slicing stays 0-copy), else the sibling .bin read into RAM."""
    try:
        return memoryview(open("/rom/" + BIN, "rb"))
    except OSError:
        with open(root + BIN, "rb") as f:
            return f.read()


def bitmap(pg, root=""):
    return pg.Bitmap(data(root), W, H, format=pg.PAL8, palette=PAL,
                     frames=FRAMES, stride=STRIDE, transparent=TRANSP)
