# Generated by tools/picolib_img.py from a PicoLibSDK image - do not edit.
# Original art (c) its PicoLibSDK author; converted to picogame PAL8.
import array

W = 8      # frame width
H = 8
FRAMES = 1
STRIDE = 8
TRANSP = 0
DATA = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0e\x0e\x0e\x0e\x00\x00\x00\t\x06\x06\x03\x05\x02\x00\t\x0b\x0b\x0b\r\x0c\r\x05\x07\x08\x08\x08\x0b\r\x0c\x08\x00\x04\x03\x07\x07\x05\n\x00\x00\x00\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
PAL = array.array("H", [8184, 31190, 64486, 44411, 3980, 53916, 27763, 52611, 11115, 30133, 6086, 35162, 34105, 50753, 57343, 0])

def bitmap(pg):
    return pg.Bitmap(DATA, W, H, format=pg.PAL8, palette=PAL,
                     frames=FRAMES, stride=STRIDE, transparent=TRANSP)
