# generated by bake_cutscene.py - RGB triplets, ONE shared palette for all scenes.
# Append-only (existing indices never move, so baked .dat files stay valid).
# The game builds the wire palette once: PAL = picogame_cutscene.palette(pg, scene_pal)
RGB = (
    (0, 0, 0),
    (255, 85, 82),
    (150, 18, 18),
    (255, 255, 82),
    (82, 85, 255),
    (245, 214, 70),
    (240, 150, 52),
    (92, 170, 245),
    (0, 0, 172),
    (172, 170, 172),
    (96, 220, 122),
    (232, 74, 74),
    (70, 70, 90),
    (255, 235, 120),
    (255, 255, 255),
    (57, 255, 255),
    (0, 255, 0),
    (172, 85, 0),
    (74, 255, 74),
    (230, 0, 0),
)
