#!/usr/bin/env python3
"""bake_cutscene.py - PNG -> raw row-major PAL8 .dat + a SHARED palette module, for picogame_cutscene.

picogame_cutscene.show() streams a raw ROW-MAJOR PAL8 file (1 byte/px, w*h bytes) from flash band-by-
band and blits it at an integer scale, so story art is baked SMALLER than the screen: the default
160x120 fills a 320x240 display at 2x for a quarter of the flash (19,200 B/scene vs 76,800).

All of a game's scenes share ONE palette module (`--pal scenes/scene_pal.py`) so the game builds a
single array('H') at setup (picogame_cutscene.palette). The module is append-only: baking a NEW scene
against an existing module re-uses its colours and only APPENDS new ones (if under --colors), so
every already-baked .dat stays valid. Re-baking ALL scenes after a big palette change is still the
better result (the first scenes never saw the later colours).

Usage:
  bake_cutscene.py in.png out.dat --pal scene_pal.py [--size 160x120] [--colors 40] [--dither]
    --pal missing  -> derive an adaptive palette from THIS image and write the module (seed it)
    --pal exists   -> quantize to it; extend with the image's most-used new colours up to --colors
  --dither     Floyd-Steinberg error diffusion (hides banding in skies/gradients on a small palette)
  --merge-dist per-channel RGB distance under which a candidate colour re-uses an existing entry

Every emitted index is < len(palette) - unlike a naive fixed-palette quantize, whose 768-byte
zero-padding lets PIL map near-black pixels to a pad slot PAST the real palette (an out-of-range
read on the device's array('H')). Pads here duplicate the last real colour and are clamped back.
"""

import argparse
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow required: pip install Pillow")

try:                                    # Pillow >= 9.1 enum; fall back to the old constants
    _DITHER_FS = Image.Dither.FLOYDSTEINBERG
    _DITHER_NONE = Image.Dither.NONE
except AttributeError:                  # pragma: no cover
    _DITHER_FS = Image.FLOYDSTEINBERG
    _DITHER_NONE = Image.NONE

_HEADER = ("# generated by bake_cutscene.py - RGB triplets, ONE shared palette for all scenes.\n"
           "# Append-only (existing indices never move, so baked .dat files stay valid).\n"
           "# The game builds the wire palette once: PAL = picogame_cutscene.palette(pg, scene_pal)\n")


def load_pal_module(path):
    """Read the RGB tuple back out of a generated (or hand-written) palette module."""
    ns = {}
    with open(path) as f:
        exec(compile(f.read(), path, "exec"), ns)
    return [tuple(c) for c in ns["RGB"]]


def write_pal_module(path, rgb):
    with open(path, "w") as f:
        f.write(_HEADER)
        f.write("RGB = (\n")
        for (r, g, b) in rgb:
            f.write("    (%d, %d, %d),\n" % (r, g, b))
        f.write(")\n")


def adaptive_colors(im, n):
    """The image's own best palette: (colour, pixel_count) pairs, most-used first."""
    q = im.quantize(colors=n, method=Image.MEDIANCUT, dither=_DITHER_NONE)
    p = q.getpalette()
    hist = q.histogram()
    used = sorted((c for c in set(q.tobytes()) if hist[c]), key=lambda c: -hist[c])
    return [((p[i * 3], p[i * 3 + 1], p[i * 3 + 2]), hist[i]) for i in used]


def extend_palette(rgb, im, cap, merge_dist):
    """Append this image's most-used colours that no existing entry covers, up to `cap`.
    A candidate within `merge_dist` per channel (RGB distance) of an existing colour is
    considered covered (re-use beats growth - the palette is shared across scenes)."""
    thresh2 = 3 * merge_dist * merge_dist
    added = 0
    for (c, _count) in adaptive_colors(im, cap):
        if len(rgb) >= cap:
            break
        near2 = min((c[0] - e[0]) ** 2 + (c[1] - e[1]) ** 2 + (c[2] - e[2]) ** 2 for e in rgb)
        if near2 > thresh2:
            rgb.append(c)
            added += 1
    return added


def quantize_fixed(im, rgb, dither):
    """Map `im` onto the FIXED palette `rgb`; every output index is guaranteed < len(rgb).
    PIL needs a 256-slot palette, so the pad slots duplicate the LAST real colour - a pixel
    that picks a pad slot matched that colour, and is clamped back to its real index."""
    n = len(rgb)
    pal_img = Image.new("P", (1, 1))
    flat = [c for t in rgb for c in t] + list(rgb[-1]) * (256 - n)
    pal_img.putpalette(flat)
    q = im.quantize(palette=pal_img, dither=_DITHER_FS if dither else _DITHER_NONE)
    idx = bytearray(q.tobytes())
    clamped = 0
    for i, v in enumerate(idx):
        if v >= n:
            idx[i] = n - 1
            clamped += 1
    return bytes(idx), clamped


def main():
    ap = argparse.ArgumentParser(description="PNG -> PAL8 .dat + shared palette module "
                                             "(picogame_cutscene scenes)")
    ap.add_argument("input", help="source PNG (any size; resized to --size)")
    ap.add_argument("output", help="output .dat (raw row-major PAL8 indices)")
    ap.add_argument("--pal", required=True,
                    help="shared palette module (.py). Missing -> seeded from this image; "
                         "existing -> re-used and extended (append-only) up to --colors")
    ap.add_argument("--size", default="160x120",
                    help="baked WxH (default 160x120 = 2x on a 320x240 screen). Must divide the "
                         "target display width for an integer scale")
    ap.add_argument("--colors", type=int, default=40,
                    help="shared-palette cap, 2..255 (default 40 - Wyrmfall shipped 9 scenes on ~39)")
    ap.add_argument("--dither", action="store_true",
                    help="Floyd-Steinberg dither (hides gradient banding on a small palette)")
    ap.add_argument("--merge-dist", type=int, default=12,
                    help="per-channel RGB distance under which a new colour re-uses an existing "
                         "palette entry instead of growing the palette (default 12)")
    a = ap.parse_args()
    a.colors = max(2, min(255, a.colors))
    w, h = (int(x) for x in a.size.lower().split("x"))

    im = Image.open(a.input).convert("RGB").resize((w, h), Image.LANCZOS)

    if os.path.exists(a.pal):
        rgb = load_pal_module(a.pal)
        if len(rgb) > 255:
            sys.exit("%s has %d colours - PAL8 tops out at 255" % (a.pal, len(rgb)))
        added = extend_palette(rgb, im, a.colors, a.merge_dist) if len(rgb) < a.colors else 0
        if added:
            write_pal_module(a.pal, rgb)
    else:
        rgb = [c for (c, _n) in adaptive_colors(im, a.colors)]
        added = len(rgb)
        write_pal_module(a.pal, rgb)

    idx, clamped = quantize_fixed(im, rgb, a.dither)
    assert len(idx) == w * h, "index buffer size mismatch (%d != %d)" % (len(idx), w * h)
    assert max(idx) < len(rgb), "index escaped the palette"
    with open(a.output, "wb") as f:
        f.write(idx)

    print("baked %s -> %s (%dx%d, %d B)  palette %s: %d colours (%+d new)%s%s" % (
        a.input, a.output, w, h, len(idx), a.pal, len(rgb), added,
        ", dithered" if a.dither else "",
        ", %d pad-slot px clamped" % clamped if clamped else ""))


if __name__ == "__main__":
    main()
