#!/usr/bin/env python3
# Bake PICO-8 tracker music into a picogame_music bank module.
#
#   python tools/p8music.py song.p8 -o my_song.py
#   python tools/p8music.py song.p8 -o my_song.py --patterns 0-7 --channels 3
#
# Reads the __sfx__ and __music__ sections of a text .p8 cartridge (author your music in
# PICO-8 or a free web clone of its tracker), keeps ONLY the sfx referenced by the selected
# patterns, and emits a compact module: SFX = {id: (speed, loop0, loop1, 32*3 bytes)} +
# PATTERNS. Prints the exact RAM footprint and every approximation it had to make.
# LICENSING: import YOUR OWN tracks (or CC0); BBS carts default to CC BY-NC-SA.
#
# Format reference: pico-8.fandom.com/wiki/P8FileFormat (notes = 5 nybbles: pitch pair,
# waveform, volume, effect; sfx header bytes: mode, speed, loop start, loop end).
import argparse
import sys


def parse_p8(path):
    sfx_lines = []
    music_lines = []
    section = None
    with open(path, "r") as f:
        for raw in f:
            line = raw.strip()
            if line.startswith("__") and line.endswith("__"):
                section = line
                continue
            if section == "__sfx__" and line:
                sfx_lines.append(line)
            elif section == "__music__" and line:
                music_lines.append(line)
    if not sfx_lines:
        sys.exit("error: no __sfx__ section (is this a text .p8, not .p8.png?)")
    return sfx_lines, music_lines


def decode_sfx(line, sid, warnings):
    if len(line) < 168:
        line = line.ljust(168, "0")
    mode = int(line[0:2], 16)
    speed = int(line[2:4], 16)
    loop0 = int(line[4:6], 16)
    loop1 = int(line[6:8], 16)
    if mode > 1:                # 0/1 = editor view mode (no audio meaning); higher bits
        warnings.add("sfx %d: filter byte 0x%02X ignored" % (sid, mode))   # = 0.2.x filters
    notes = bytearray()
    for i in range(32):
        h = line[8 + i * 5: 13 + i * 5]
        pitch = int(h[0:2], 16) & 63
        wave = int(h[2], 16)
        vol = int(h[3], 16) & 7
        fx = int(h[4], 16) & 7
        if wave > 7:
            warnings.add("sfx %d: custom instrument %d -> square" % (sid, wave))
            wave = 3
        notes.append(pitch)
        notes.append((wave << 4) | vol)
        notes.append(fx)
    return speed, loop0, loop1, bytes(notes)


def decode_music(line):
    parts = line.split()
    if len(parts) != 2 or len(parts[1]) != 8:
        return None
    flags = int(parts[0], 16) & 7
    chans = []
    for k in range(4):
        b = int(parts[1][k * 2: k * 2 + 2], 16)
        chans.append(0xFF if b & 0x40 else (b & 0x3F))
    return chans[0], chans[1], chans[2], chans[3], flags


def main():
    ap = argparse.ArgumentParser(description="PICO-8 .p8 music -> picogame_music bank")
    ap.add_argument("p8")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--patterns", default=None,
                    help="pattern range 'A-B' or single index (default: up to the first "
                         "all-empty pattern)")
    ap.add_argument("--channels", type=int, default=4,
                    help="keep at most N channels (music CPU on RP2040 ~0.75 ms each; "
                         "drops the highest channel numbers first)")
    args = ap.parse_args()

    sfx_lines, music_lines = parse_p8(args.p8)
    warnings = set()

    rows = []
    for line in music_lines:
        r = decode_music(line)
        if r is not None:
            rows.append(r)
    if args.patterns:
        if "-" in args.patterns:
            a, b = (int(x) for x in args.patterns.split("-"))
        else:
            a = b = int(args.patterns)
        rows = rows[a:b + 1]
    else:
        for end, r in enumerate(rows):
            if all(c == 0xFF for c in r[:4]):
                rows = rows[:end]
                break
    if not rows:
        sys.exit("error: no music patterns selected")

    if args.channels < 4:
        rows = [tuple(list(r[:args.channels]) + [0xFF] * (4 - args.channels) + [r[4]])
                for r in rows]
        warnings.add("channels limited to %d (--channels)" % args.channels)

    used = sorted({c for r in rows for c in r[:4] if c != 0xFF})
    sfx = {}
    for sid in used:
        if sid >= len(sfx_lines):
            sys.exit("error: pattern references sfx %d beyond __sfx__" % sid)
        sfx[sid] = decode_sfx(sfx_lines[sid], sid, warnings)

    with open(args.out, "w") as f:
        f.write("# generated by tools/p8music.py from %s - do not edit\n" % args.p8)
        f.write("SFX = {\n")
        for sid in used:
            speed, l0, l1, notes = sfx[sid]
            f.write("    %d: (%d, %d, %d, %r),\n" % (sid, speed, l0, l1, notes))
        f.write("}\n\nPATTERNS = (\n")
        for r in rows:
            f.write("    (%d, %d, %d, %d, %d),\n" % r)
        f.write(")\n")

    bank = sum(96 for _ in used)
    print("baked %d pattern(s), %d sfx -> %s" % (len(rows), len(used), args.out))
    print("device RAM: ~%d B song bank + ~256 B per used waveform + player <1 KB"
          % (bank + len(rows) * 40))
    for w in sorted(warnings):
        print("note:", w)


if __name__ == "__main__":
    main()
